### ISSUE TITLE
Unable to build due to libheif-rs and libheif-sys mismatch

### ISSUE THREAD

**Issue by rider695** [Cykooz/cykooz.heif#1]
When installing the package from pip the compiling fails on the libheif-rs rust package step.

```
error[E0063]: missing fields `macOS_compatibility_workaround`, `save_two_colr_boxes_when_ICC_and_nclx_available` in initializer of `heif_encoding_options`
   --> /home/rob/.cargo/registry/src/github.com-1ecc6299db9ec823/libheif-rs-0.11.0/src/encoder.rs:175:9
    |
175 |         lh::heif_encoding_options {
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^ missing `macOS_compatibility_workaround`, `save_two_colr_boxes_when_ICC_and_nclx_available`
```

I have no experience with rust but looking at the 2 repos points me to 
https://github.com/Cykooz/libheif-rs/blob/398bfadcaf59fb7b48559693e69bd583f6aa536d/src/encoder.rs#L154 
missing the newly added fields from 
https://github.com/Cykooz/libheif-sys/blob/3e4573b10084760c093789604debd778bfd6a5e2/src/bindings.rs#L1582

How to reproduce:
`pip install cykooz.heif`

**Comment by Cykooz** [comment]
I will try to release the new version of ``libheif-rs`` and ``cykooz.heif`` as soon as possible.

**Comment by Cykooz** [comment]
I've released a new version of ``cykooz.heif`` 0.10. Try to install it.
