### ISSUE TITLE
Python 3.10 wheels

### ISSUE THREAD

**Issue by nickovs** [Cykooz/cykooz.heif#3]
The Docker [build script](https://github.com/Cykooz/cykooz.heif/blob/cfd60687406763503a57fe949bdf01fb9997cae8/docker/Dockerfile#L170-L177) for wheels currently builds for Python 3.6 through 3.9. Now that Python 3.10 is out and gaining traction it would be hugely helpful to the community if you could add 3.10 to this list and push a wheel for 3.10 to to PyPI.

By the way, thank you very much for creating this!

**Comment by d0tcc** [comment]
I would also be very interested in a wheel that works in Python 3.10!
Is there any way we could help?

Thanks for the great work!
